excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://castrojo.github.io
title: Jorge's Stompbox
tagline: Plug in, crank it to eleven.
description: Plug in, crank it to eleven.
paginate: 7
permalink: /:year/:month/:day/:title/
titlecase: true
